title: "Kankakee Community College"
port: 3000
timezone: America/Chicago
public-url: https://athletics.kcc.edu
url: "https://athletics.kcc.edu" # the base hostname & protocol for your site
google-tag_key: 'GTM-KRL8533'
# BUILD
collections:
  posts:
    output: false
  accordions:
    output: false
  staff:
    output: false
  contacts:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    post_title: ''
    permalink: /:categories/:title/
    baseurl: ../../../../
- scope:
    path: ''
    type: alerts
  values:
    title: ''
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  KCC offers intercollegiate men's basketball, women's basketball, baseball, softball, men's soccer and volleyball. The Cavaliers compete in Region IV of the NJCAA.
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# Output posts with dates that havent happened (future posts):
future: true
# Build settings
markdown: kramdown

sass: # Use jekyll to compile a simple CloudCannon (CC) stylesheet found in `/assets/css/content.scss`
  sass_dir: /assets/scss/ # tell Jekyll where our sass partials are (default is _sass/)
  sourcemap: never # Jekyll command breaks with default sourcemap settings - it's tiny stylesheet anyways
  style: expanded # CC requires an expanded css file for custom CC styles

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "webpack.config.js"
  - "postcss.config.js"
  - "buildtools/"
  - "siteicon.png"
  - "look-for-deprecated-bs4-classes.mjs"
  - "look-for-deprecated-bs4-js.mjs"

uploads_dir: "uploads/" # specifies the default uploads directory for CloudCannon

contacts_sports:
  baseball: Baseball
  men's basketball: Mens's Basketball
  soccer: Soccer
  women's basketball: Women's Basketball
  softball: Softball
  volleyball: Volleyball
  women's soccer: Women's Soccer

_select_data:
  post_topics:
    - General News
    - Baseball
    - Softball
    - Men's Basketball
    - Women's Basketball
    - Soccer
    - Volleyball
  categories:
    general: General
    baseball: Baseball
    softball: Softball
    mens-basketball: "Men's Basketball"
    womens-basketball: "Women's Basketball"
    soccer: Soccer
    volleyball: Volleyball

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
  include_gapi:
    hidden: true
  include_datatables:
    hidden: true
  include_sub-nav:
    hidden: true
  sport_sub_nav:
    hidden: true
  content:
    format: p h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
