title: "Kankakee Community College"
collections:
  news:
    title: News
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: releases
  values:
    layout: news-page
    title:
    description:
    news-release_date:
    release_thumb_path: "/siteicon.png"
    for_media: true
    expires_date:
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  KCC offers intercollegiate men's basketball, women's basketball, baseball, softball, men's soccer and volleyball. The Cavaliers compete in Region IV of the NJCAA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
include:
  - "_uploads"
#   - "_pages"
#   - "_posts"
exclude:
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/docs/"
  - "yarn.lock"
  - "/assets/adobe/"
