title: "Kankakee Community College"
collections:
  posts:
    output: false
    _hide_content: true
  alerts:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
- scope:
    path: ''
    type: alerts
  values:
    title: ''
- scope:
    path: ''
    type: releases
  values:
    layout: news-page
    title:
    description:
    news-release_date:
    release_thumb_path: "/siteicon.png"
    for_media: true
    expires_date:
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  KCC offers intercollegiate men's basketball, women's basketball, baseball, softball, men's soccer and volleyball. The Cavaliers compete in Region IV of the NJCAA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
# include:
#   - "_pages"
#   - "_posts"

future: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - liquid-md5

exclude:
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/docs/"
  - "yarn.lock"
  - "/assets/adobe/"

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  sport: "# Value dictates which schedule is pulled: <br/>\"1\" = All sports <br/>\"2\" = Baseball <br/>\"3\" = Softball <br/>\"4\" = Volleyball <br/>\"5\" = Soccer <br/>\"6\" = Women's Basketball <br/>\"7\" = Men's Basketball"
