browsersync:
  notify: true
  open:   false # set to true to open localhost:3000 in chrome browser upon execution of gulp command.
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

clean:
  # The jekyll build dir
  - "_site" # clean these folders on execution of gulp command
#  - "_posts/*"

copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  # The two comments above this one came from the template.
  # We copy all JS and SCSS because Google Chrome Inspect will tell you where the style is located within the sass structure.
  assets:
    # all files below the assets dir
    # everything gets copied to site build becuase some JS files are linked directly into pages and not compiled into all.min.js)
    - "assets/**/*"
    # exclusions: (Don't copy these items because they are handled by other gulp tasks)
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running Copy"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/main.scss"

javascript:
  dest:
    jekyllRoot: "assets/js/"
    buildDir: "_site/assets/js/"
  filename: "all.min.js"
  notification: "Running JavaScript"
  src:
    # Exclusions: (!exclaim to exclude)
    - "!assets/js/all.js"
    - "!assets/js/schedule-pages.js" # needed for schedule pages only
    - "!assets/js/initSchedulePage.js" # needed to initiate schedules (used in schedule-page-script.html)
    - "!assets/js/lazyLoadOnly.js" # needed to lazyload on pages with no youtube slider (youtube-carousel.js calls the lazyload function on those pages)
    - "!assets/js/StickyTableHeader.js" # Small sticky table header jquery library for on schedule pages only
    - "!assets/js/StickyTableCustom.js" # Custom JS to initiate the afforementioned small sticky table header jquery library
    - "assets/js/sliders.js" # custom slick slider JS
    - "assets/js/schedule.js" # Custom JS for schedule pages
    - "assets/js/youtube-carousel.js" # Custom JS for YouTube video carousel
    - "assets/js/init.js" # Initiate the schedule.js
    - "assets/js/lazyload.js" # lazload.js called within youtube-carousel.js

sitemap:
  src:
    - "_site/*.html"
    - "_site/**/*.html"
    - "_site/**/**/*.html"
  siteUrl:
    - "http://athletics.kcc.edu"

jekyll:
  notification: "Running jekyll"

watch: # 'Watch' for changes in all the following:
  images: "assets/img/**/*"
  javascript:
    - "assets/js/all.min.js"
    - "assets/js/*.js"
  sass: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts,_alerts}/**/*.{md,html,yml,xml}"
    # All these subfolders are added because the watch task was not looking deep enough
    - "about/**/*.*"
    - "baseball/**/*.*"
    - "facilities/**/*.*"
    - "mens-basketball/**/*.*"
    - "soccer/**/*.*"
    - "softball/**/*.*"
    - "support/**/*.*"
    - "volleyball/**/*.*"
    - "womens-basketball/**/*.*"
    # !exlclusions:
    - "!_site/**/*.*"
    - "!assets/**/*.*"
