browsersync:
  notify: true
  open:   false # set to true to open localhost:3000 in chrome browser upon execution of gulp command.
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

clean:
  # The jekyll build dir
  - "_site" # clean these folders on execution of gulp command
#  - "_posts/*"

copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  # The two comments above this one came from the template.
  # We copy all JS and SCSS because Google Chrome Inspect will tell you where the style is located within the sass structure.
  assets:
    # all files below the assets dir
    # everything gets copied to site build becuase some JS files are linked directly into pages and not compiled into all.min.js)
    - "assets/**/*"
    # exclusions: (Don't copy these items because they are handled by other gulp tasks)
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running Copy"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/main.scss"

contentSass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running contentSass"
  src: "assets/scss/content.scss"

javascript:
  dest:
    jekyllRoot: "assets/js/script/"
    buildDir: "_site/assets/js/script/"
  filename: "all.min.js"
  notification: "Running JavaScript"
  src:
    - "assets/js/script/sliders.js" # custom slick slider JS
    - "!assets/js/script/schedule-old.js" # Custom JS for schedule pages
    - "assets/js/script/youtube-carousel.js" # Custom JS for YouTube video carousel
    - "assets/js/script/init.js" # Initiate the schedule.js
    - "assets/js/script/lazyload.js" # lazload.js called within youtube-carousel.js
    - "assets/js/script/moreButton.js"
    - "assets/js/script/schedule.js"

javascriptSlim:
  dest:
    jekyllRoot: "assets/js/slim/"
    buildDir: "_site/assets/js/slim/"
  filename: "all.slim.min.js"
  notification: "Running JavaScript Slim"
  src:
    - "assets/js/slim/lazyload.js" # lazload.js called within youtube-carousel.js
    - "assets/js/slim/accordian.js"
    - "!assets/js/slim/table.js"

javascriptSchedule:
  dest:
    jekyllRoot: "assets/js/schedule/"
    buildDir: "_site/assets/js/schedule/"
  filename: "schedule.min.js"
  notification: "Running JavaScript Schedule"
  src:
    - "!assets/js/schedule/stickyTableHeader.js"
    - "!assets/js/schedule/stickyTableCustom.js"
    - "!assets/js/schedule/schedule-pages.js"
    - "!assets/js/schedule/initSchedulePage.js"
    - "!assets/js/schedule/scheduleTable.js"
    - "!assets/js/schedule/scheduleTableDev.js"
    - "assets/js/schedule/scheduleTableDevelopment.js"

javascriptLazy:
  dest:
    jekyllRoot: "assets/js/lazy/"
    buildDir: "_site/assets/js/lazy/"
  filename: "lazyLoad.min.js"
  notification: "Running Lazy Load JavaScript"
  src:
    - "assets/js/lazy/lazyLoadOnly.js"

sitemap:
  src:
    - "_site/*.html"
    - "_site/**/*.html"
    - "_site/**/**/*.html"
    - "_site/**/*.pdf"
    - "_site/**/**/*.pdf"
  siteUrl:
    - "https://athletics.kcc.edu"

jekyll:
  notification: "Running jekyll"

watch: # 'Watch' for changes in all the following:
  images: "assets/img/**/*"
  javascript:
    - "assets/js/script/all.min.js"
    - "assets/js/script/*.js"
    - "assets/js/schedule/schedule.min.js"
    - "assets/js/schedule/*.js"
    - "assets/js/lazy/lazyLoad.min.js"
    - "assets/js/lazy/*.js"
    - "assets/js/slim/all.slim.min.js"
    - "assets/js/slim/*.js"
  sass: "assets/scss/**/*.scss"
  contentSass: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts,_alerts}/**/*.{md,html,yml,xml}"
    # All these subfolders are added because the watch task was not looking deep enough
    - "about/**/*.*"
    - "baseball/**/*.*"
    - "facilities/**/*.*"
    - "mens-basketball/**/*.*"
    - "soccer/**/*.*"
    - "softball/**/*.*"
    - "support/**/*.*"
    - "volleyball/**/*.*"
    - "womens-basketball/**/*.*"
    # !exlclusions:
    - "!_site/**/*.*"
    - "!assets/**/*.*"
